steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-react-app', '.']
images:
  - 'gcr.io/$PROJECT_ID/my-react-app'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
